services:
  dev:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    image: job-alerter-dev:latest
    container_name: job-alerter-dev
    working_dir: /work
    volumes:
      - .:/work:cached
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    command: bash -lc "sleep infinity"
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 2g
    # For Docker Desktop: you can pause this container when not in use
